// Visualization module for LeetVision

// Initialize namespace if it doesn't exist
window.LeetVision = window.LeetVision || {};

// Visualization handler class
class VisualizationHandler {
  constructor() {
    this.visualizationCache = new Map();
  }
  
  /**
   * Creates a visualization for a problem
   * @param {string} problemType - The type of problem (array, string, etc.)
   * @param {string} d3Code - The D3.js code generated by the LLM
   * @param {HTMLElement} container - The container element to render the visualization in
   */
  createVisualization(problemType, d3Code, container) {
    switch (problemType.toLowerCase()) {
      case 'array':
        this.createArrayVisualization(d3Code, container);
        break;
      case 'string':
        this.createStringVisualization(d3Code, container);
        break;
      default:
        // Fallback to generic visualization
        this.createGenericVisualization(d3Code, container);
    }
  }
  
  /**
   * Creates an array-specific visualization
   * @param {string} d3Code - The D3.js code generated by the LLM
   * @param {HTMLElement} container - The container element to render the visualization in
   */
  createArrayVisualization(d3Code, container) {
    // Use the generic visualization for now
    this.createGenericVisualization(d3Code, container);
  }
  
  /**
   * Creates a string-specific visualization
   * @param {string} d3Code - The D3.js code generated by the LLM
   * @param {HTMLElement} container - The container element to render the visualization in
   */
  createStringVisualization(d3Code, container) {
    // Use the generic visualization for now
    this.createGenericVisualization(d3Code, container);
  }
  
  /**
   * Creates a generic visualization
   * @param {string} d3Code - The D3.js code generated by the LLM
   * @param {HTMLElement} container - The container element to render the visualization in
   */
  createGenericVisualization(d3Code, container) {
    // Create a sandbox iframe to run the D3 code
    const iframe = document.createElement('iframe');
    iframe.style.width = '100%';
    iframe.style.height = '100%';
    iframe.style.border = 'none';
    
    container.innerHTML = '';
    container.appendChild(iframe);
    
    // Prepare the HTML content with D3.js
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <script src="https://d3js.org/d3.v7.min.js"></script>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            overflow: hidden;
          }
          #visualization {
            width: 100%;
            height: 100vh;
          }
          .controls {
            position: absolute;
            bottom: 10px;
            left: 50%;
            transform: translateX(-50%);
            display: flex;
            gap: 10px;
            background: rgba(255, 255, 255, 0.9);
            padding: 5px 10px;
            border-radius: 4px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
          }
          button {
            padding: 5px 10px;
            border: none;
            background: #0078d7;
            color: white;
            border-radius: 4px;
            cursor: pointer;
          }
          button:hover {
            background: #005a9e;
          }
          button:disabled {
            background: #cccccc;
            cursor: not-allowed;
          }
          
          /* Dark mode compatibility */
          @media (prefers-color-scheme: dark) {
            body {
              background-color: #1e1e1e;
              color: #f0f0f0;
            }
            .controls {
              background: rgba(40, 40, 40, 0.9);
            }
          }
        </style>
      </head>
      <body>
        <div id="visualization"></div>
        <script>
          ${d3Code}
        </script>
      </body>
      </html>
    `;
    
    iframe.srcdoc = html;
  }
  
  /**
   * Caches a visualization for later use
   * @param {string} problemId - The unique identifier for the problem
   * @param {Object} visualizationData - The visualization data to cache
   */
  cacheVisualization(problemId, visualizationData) {
    this.visualizationCache.set(problemId, visualizationData);
  }
  
  /**
   * Retrieves a cached visualization
   * @param {string} problemId - The unique identifier for the problem
   * @returns {Object|null} - The cached visualization data, or null if not found
   */
  getCachedVisualization(problemId) {
    return this.visualizationCache.get(problemId) || null;
  }
}

// Export visualization handler
window.LeetVision.visualization = new VisualizationHandler(); 